Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {

	Route::group( array("prefix" => "admin", "as"=>"admin."), function() {

    	Route::group(['middleware' => 'auth:dcms'], function() {

			//Advices
			Route::group( array("prefix" => "frontendusers" ,"as"=>"frontendusers."), function() {
      			//API
      			Route::group( array("prefix" => "api", "as"=>"api."), function() {
      				Route::any('table', array('as'=>'table', 'uses' => 'FrontendusersController@getDatatable'));
      			});
      		});

      		Route::resource('frontendusers','FrontendusersController');
    });
  });
});

 ?>

Models/Users.php
<?php

namespace Dcms\Frontendusers\Models;

use Dcms\Core\Models\EloquentDefaults;

class Users extends EloquentDefaults
{
    protected $connection = 'project';
    protected $table = 'customers';
}

Http/Controllers/FrontendusersController.php
<?php

namespace Dcms\Frontendusers\Http\Controllers;

use App\Http\Controllers\Controller;
use Dcms\Frontendusers\Models\Users;
use Illuminate\Http\Request;
use View;
use Input;
use Session;
use Validator;
use Redirect;
use DB;
use Datatables;
use Auth;
use Form;
use DateTime;

class FrontendusersController extends Controller
{
    public function __construct()
    {
        $this->middleware('permission:gardenusers-browse')->only('index');
        $this->middleware('permission:gardenusers-add')->only(['create', 'store']);
        $this->middleware('permission:gardenusers-edit')->only(['edit', 'update']);
        $this->middleware('permission:gardenusers-delete')->only('destroy');
    }

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        // load the view
        return View::make('dcms::frontendusers/index');
    }

    public function getDatatable()
    {
        return Datatables::queryBuilder(
            DB::connection('project')->table('customers')
                ->select(
                    'id',
                    'email',
                    'firstname',
                    'lastname',
                    'companyname',
                    'client',
                    (DB::connection("gardeneering")->raw('Concat("<img src=\'/packages/Dcms/Core/images/flag-",lcase(country),".png\' >") as country'))
                )
                ->orderBy('email')
        )
            ->addColumn('edit', function ($model) {
                $edit = '<form method="POST" action="/admin/frontendusers/' . $model->id . '" accept-charset="UTF-8" class="pull-right">
								<input name="_token" type="hidden" value="' . csrf_token() . '">
                                <input name="_method" type="hidden" value="DELETE">';
                       
                if (Auth::user()->can('gardenusers-edit')) {
                    $edit .= '<a class="btn btn-xs btn-default" href="/admin/frontendusers/' . $model->id . '/edit"><i class="far fa-pencil"></i></a>';
                }
                
                if (Auth::user()->can('gardenusers-delete')) {
                    $edit .= '<button class="btn btn-xs btn-default" type="submit" value="Delete this user" onclick="if(!confirm(\'Are you sure to delete this item?\')){return false;};"><i class="far fa-trash-alt"></i></button>';
                }
                $edit .= '</form>';
                            
                return $edit;
            })
            ->rawColumns(['country', 'edit'])
            ->make(true);
    }

    public function getExtendedModel()
    {
        //do nothing let the extend class hook into this
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        $user = new Users();
        return View::make('dcms::frontendusers/form')
            ->with('user', $user);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $user = Users::findOrFail($id);
        return View::make('dcms::frontendusers/form')
            ->with('user', $user);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return Response
     */
    public function store(Request $request)
    {
        if ($this->validateUserForm($request) === true) {
            $user = new Users();
            if ($this->emailExists($request->email) === false) {
                $user = $this->processUserForm($user, $request);

                // redirect
                Session::flash('message', 'Successfully created user!');
                return redirect()->route('admin.frontendusers.index');
            } else {
                return $this->emailExists($request->email);
            }
        } else {
            return $this->validateUserForm($request);
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function update(Request $request, $id)
    {
        if ($this->validateUserForm($request) === true) {
            $user = Users::findOrFail($id);

            if (strtolower($user->email) <> trim(strtolower($request->email))) {
                if ($this->emailExists($request->email) !== false) {
                    return $this->emailExists($request->email);
                }
            }

            $user = $this->processUserForm($user, $request);

            // redirect
            Session::flash('message', 'Successfully updated user!');
            return redirect()->route('admin.frontendusers.index');
        } else {
            return $this->validateUserForm($request);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        Users::where('id', $id)->delete();
        return Redirect::to('admin/frontendusers');
    }

    private function emailExists($email = null)
    {
        if (Users::where('email', '=', $email)->exists()) {
            return Redirect::back()->withErrors(['email'=>'This email adress is allready used by another account'])->withInput();
        }
        return false;
    }

    private function validateUserForm(Request $request)
    {
        $rules = [
            'email' => 'required|email'
        ];
        $validator = Validator::make($request->all(), $rules);

        if ($validator->fails()) {
            return Redirect::back()->withErrors($validator)->withInput();
        } else {
            return true;
        }
    }

    private function processUserForm($user, $request)
    {
        $user->country = $request->country;
        $user->language = $request->language;
        $user->email = $request->email;
        $user->companyname = $request->get('companyname');
        $user->client = $request->get('client');
        $user->firstname = $request->get('firstname');
        $user->lastname = $request->get('lastname');
        $user->comment = $request->get('code');
        $user->retailapproved = ($request->get('retailapproved')==1 ? 1 : 0);

        $user->save();

        return $user;
    }
}

resources/views/frontendusers/form.blade.php
@extends("dcms::template/layout")

@section("content")

    <div class="main-header">
        <h1>Garden users</h1>
        <ol class="breadcrumb">
            <li><a href="{!! URL::to('admin/dashboard') !!}"><i class="far fa-tachometer-alt-average"></i> Dashboard</a></li>
            <li><a href="{!! URL::to('admin/frontendusers') !!}"><i class="far fa-pencil"></i> Garden users</a></li>
            @if($user->exists)
                <li class="active">Edit</li>
            @else
                <li class="active">Create</li>
            @endif
        </ol>
    </div>

    <div class="main-content">
        @if($user->exists)
        <form action="{{ route('admin.frontendusers.update', $user->id) }}" method="post">
            {{ method_field('PUT') }}
        @else
        <form action="{{ route('admin.frontendusers.store') }}" method="post">
        @endif
        {!! csrf_field() !!}
        <div class="row">
            <div class="col-md-9">
                <div class="main-content-tab tab-container">
                    <ul class="nav nav-tabs" role="tablist">
                        <li class="active"><a href="#data" role="tab" data-toggle="tab">Data</a></li>
                        @yield('extratabs')
                    </ul>

                    <div class="tab-content">
                        <!-- Data -->
                        <div id="data" class="tab-pane active">
                            <div class="tab-content">

                                <div class="form-group">
                                    <label for="email">E-mail</label>
                                    <input type="text" class="form-control" id="email" name="email" value="{{ $user->email }}">
                                </div>

                                <div class="form-group">
                                    <label for="lastname">Lastname</label>
                                    <input type="text" class="form-control" id="lastname" name="lastname" value="{{ $user->lastname }}">
                                </div>

                                <div class="form-group">
                                    <label for="firstname">Firstname</label>
                                    <input type="text" class="form-control" id="firstname" name="firstname" value="{{ $user->firstname }}">
                                </div>

                                <div class="form-group">
                                    <label for="email">Country</label>
                                    <select name="country">
                                        @foreach(['BE','NL','LU','DE','FR'] as $country)
                                            <option value="{{ $country }}" @if($user->country == $country) selected @endif >{{ $country }}</option>
                                        @endforeach
                                    </select>
                                </div>

                                <div class="form-group">
                                    <label for="email">Language</label>
                                    <select name="language">
                                        @foreach(['nl','fr','de'] as $language)
                                            <option value="{{ $language }}" @if($user->language == $language) selected @endif >{{ $language }}</option>
                                        @endforeach
                                    </select>
                                </div>

                                <div class="form-group">
                                    <label for="retail">Retail enabled</label>
                                    <input type="checkbox" class="" id="retailapproved" name="retailapproved" value="1" @if($user->retailapproved == "1") checked @endif>
                                </div>

                                <div class="form-group">
                                    <label for="companyname">Company</label>
                                    <input type="text" class="form-control" id="companyname" name="companyname" value="{{ $user->companyname }}">
                                </div>

                                <div class="form-group">
                                    <label for="code">Code (SAP)</label>
                                    <input type="text" class="form-control" id="code" name="code" value="{{ $user->comment }}">
                                </div>

                                <div class="form-group">
                                    <input type="checkbox" name="client" id="client" value="1" class="form-checkbox" {{ $user->client ? 'checked' : '' }}>
                                    <label for="client" class="checkbox {{ $user->client ? 'active' : '' }}">Client</label>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="main-content-block">
                    {!! Form::submit('Save', array('class' => 'btn btn-primary')) !!}
                    <a href="{!! URL::previous() !!}" class="btn btn-default">Cancel</a>
                </div>
            </div>
        </div>
        </form>
    </div>

@stop

@section("script")
    <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/plug-ins/be7019ee387/integration/bootstrap/3/dataTables.bootstrap.css">

    <script type="text/javascript" language="javascript" src="//cdn.datatables.net/1.10.0/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" language="javascript" src="//cdn.datatables.net/plug-ins/be7019ee387/integration/bootstrap/3/dataTables.bootstrap.js"></script>

    <script type="text/javascript" src="{!! asset('/packages/Dcms/Core/js/bootstrap.min.js') !!}"></script>
    <script type="text/javascript" src="{!! asset('/packages/Dcms/Core/ckeditor/ckeditor.js') !!}"></script>
    <script type="text/javascript" src="{!! asset('/packages/Dcms/Core/ckeditor/adapters/jquery.js') !!}"></script>
    <script type="text/javascript" src="{!! asset('/packages/Dcms/Core//ckfinder/ckfinder.js') !!}"></script>
    <script type="text/javascript" src="{!! asset('/packages/Dcms/Core//ckfinder/ckbrowser.js') !!}"></script>

    <script type="text/javascript">
        $(document).ready(function () {

            //CKFinder for CKEditor
            CKFinder.setupCKEditor(null, '/packages/Dcms/Core/ckfinder/');

            //CKEditor
            $("textarea[id='description']").ckeditor();
            $("textarea[id='body']").ckeditor();

            //Bootstrap Tabs
            $(".tab-container .nav-tabs a").click(function (e) {
                e.preventDefault();
                $(this).tab('show');
            });
        });
    </script>

@stop

resources/views/frontendusers/index.blade.php
@extends("dcms::template/layout")

@section("content")

    <div class="main-header">
      <h1>Garden users</h1>
      <ol class="breadcrumb">
        <li><a href="{!! URL::to('admin/dashboard') !!}"><i class="far fa-tachometer-alt-average"></i> Dashboard</a></li>
        <li class="active"><i class="far fa-pencil"></i> Garden users</li>
      </ol>
    </div>

    <div class="main-content">
    	<div class="row">
				<div class="col-md-12">
					<div class="main-content-block">

  @if (Session::has('message'))
    <div class="alert alert-info">{!! Session::get('message') !!}</div>
  @endif

    <div class="btnbar btnbar-right"><a class="btn btn-small btn-primary" href="{!! URL::to('/admin/frontendusers/create') !!}">Create new</a></div>

    <h2>Overview</h2>

        <table id="datatable" class="table table-hover table-condensed" style="width:100%">
            <thead>
                <tr>
                    <th>Email</th>
                    <th>Firstname</th>
                    <th>Lastname</th>
                    <th>Companyname</th>
                    <th>Client</th>
                    <th>Country</th>
                    <th></th>
                </tr>
            </thead>
        </table>

    <script type="text/javascript">
        $(document).ready(function() {
            oTable = $('#datatable').DataTable({
                "pageLength": 50,
                "processing": true,
                "serverSide": true,
                "ajax": "{{ route('admin.frontendusers.api.table') }}",
                "columns": [
                    {data: 'email', name: 'email'},
                    {data: 'firstname', name: 'firstname'},
                    {data: 'lastname', name: 'lastname'},
                    {data: 'companyname', name: 'companyname'},
                    {data: 'client', name: 'client'},
                    {data: 'country', name: 'country', searchable: false},
                    {data: 'edit', name: 'edit', orderable: false, searchable: false}
                ]
            });
        });
    </script>

    <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/plug-ins/be7019ee387/integration/bootstrap/3/dataTables.bootstrap.css">

    <script type="text/javascript" language="javascript" src="//cdn.datatables.net/1.10.0/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" language="javascript" src="//cdn.datatables.net/plug-ins/be7019ee387/integration/bootstrap/3/dataTables.bootstrap.js"></script>

	      	</div>
      	</div>
      </div>
    </div>

@stop